# Generated by Django 3.2.5 on 2022-02-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='img', verbose_name='Аватар'),
        ),
    ]
