# Generated by Django 3.2.5 on 2022-04-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Course',
        ),
    ]
