# Generated by Django 4.0.2 on 2022-03-16 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
