# Generated by Django 3.2.5 on 2022-02-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
