# Generated by Django 4.0.4 on 2022-05-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='BastauApp.partner', verbose_name='Организации'),
        ),
    ]
