# Generated by Django 4.0 on 2022-02-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='FistName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='MidlleName',
        ),
        migrations.AddField(
            model_name='partner',
            name='Fio',
            field=models.CharField(blank=True, max_length=100, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='student',
            name='Fio',
            field=models.CharField(blank=True, max_length=100, verbose_name='ФИО'),
        ),
    ]
