# Generated by Django 3.2.5 on 2022-02-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0002_alter_answer_is_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_won',
            field=models.CharField(choices=[('Участник', 'Участник'), ('Победитель', 'Победитель')], default=('Участник', 'Участник'), max_length=20, verbose_name='Победитель'),
        ),
    ]
