# Generated by Django 3.2.5 on 2022-03-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0002_alter_answer_id_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_won',
            field=models.BooleanField(default=False),
        ),
    ]
