# Generated by Django 4.0 on 2022-02-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0003_alter_answer_id_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='File',
            field=models.FileField(upload_to='file', verbose_name='Файл'),
        ),
    ]
