# Generated by Django 4.0 on 2022-02-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0003_remove_user_fistname_remove_user_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_stuff',
        ),
    ]
