# Generated by Django 3.2.5 on 2022-05-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0003_auto_20220519_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Отказ', 'Отказ'), ('Победа', 'Победа')], default=('Ожидание', 'Ожидание'), max_length=50, verbose_name='Статус'),
        ),
    ]
