# Generated by Django 4.0 on 2022-02-20 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0004_alter_answer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id_case',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BastauApp.case', verbose_name='id_case'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id_student',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BastauApp.user', verbose_name='id_student'),
        ),
    ]
