# Generated by Django 4.0 on 2022-02-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0004_alter_answer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_won',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='File',
            field=models.FileField(blank=True, upload_to='file', verbose_name='Файл'),
        ),
    ]
