# Generated by Django 4.0 on 2022-02-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0004_rename_is_staff_user_is_stuff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
