# Generated by Django 4.0.4 on 2022-05-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0002_alter_case_user_id'),
        ('BastauApp', '0004_alter_answer_status'),
    ]

    operations = [
    ]
