# Generated by Django 4.0 on 2022-02-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0005_case_is_won_alter_answer_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='is_won',
        ),
        migrations.AddField(
            model_name='student',
            name='is_won',
            field=models.BooleanField(default=False),
        ),
    ]
