# Generated by Django 4.0 on 2022-02-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0006_alter_answer_options_alter_case_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Студент', 'Студент'), ('Партнер', 'Партнер')], default=('Студент', 'Студент'), max_length=10),
        ),
    ]
