# Generated by Django 3.2.5 on 2022-02-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0006_alter_answer_id_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Аватар'),
        ),
    ]
