# Generated by Django 4.0 on 2022-02-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0007_remove_student_is_won_user_is_won'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_won',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_won',
            field=models.BooleanField(default=False),
        ),
    ]
