# Generated by Django 4.0 on 2022-02-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0008_remove_user_is_won_answer_is_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_won',
            field=models.CharField(choices=[('Победитель', 'Победитель'), ('Участник', 'Участник')], default=('Участник', 'Участник'), max_length=50),
        ),
    ]
