# Generated by Django 4.0 on 2022-02-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0010_alter_answer_is_won'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_won',
        ),
    ]
